[package]
name = "grib"
version = "0.1.0"
authors = ["Matthew Iannucci <mpiannucci@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grib-types = { path = "./types" }
grib-macros = { path = "./macros" }
chrono = "0.4"
openjpeg-sys = "1.0.1"
num = "0.2.1"

[dev-dependencies]
reqwest = { version = "0.10" }
tokio = { version = "0.2", features = ["full"] }
csv = "1.1"
futures = "0.3"
bytes = "0.5"
