[package]
name = "gribberish-python"
version = "0.1.0"
authors = ["Matthew Iannucci <mpiannucci@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gribberish"
crate-type = ["cdylib"]

[dependencies]
gribberish = { path = "../" }
numpy = "0.14.1"

[dependencies.pyo3]
version = "0.14.3"
features = ["extension-module"]
