[package]
name = "gribberish-python"
version = "0.1.0"
authors = ["Matthew Iannucci <mpiannucci@gmail.com>"]
edition = "2021"

[lib]
name = "gribberishpy"
crate-type = ["cdylib"]

[dependencies]
gribberish = { path = "../" }
numpy = "0.17.2"

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module"]
